# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  name: Azure Pipelines
  demands: maven


steps:

- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: 'day-trader-java-app/pom.xml'

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'daytrader2'

#- task: Maven@3
#  inputs:
#    mavenPomFile: 'day-trader-java-app/pom.xml'
#    goals: 'deploy'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    mavenVersionOption: 'Default'
#    mavenAuthenticateFeed: false
#    effectivePomSkip: false
#    sonarQubeRunAnalysis: false

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()


#- task: PublishBuildArtifacts@1
#  displayName: 'Publish Artifact: drop'
#  inputs:
#    PathtoPublish: '$(build.artifactstagingdirectory)'
#    artifactName: JAVA_Drop
#  condition: succeededOrFailed()


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(system.defaultworkingdirectory)'
    artifact: '10_JAVA'
    publishLocation: 'pipeline'