trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '3d034576-aa51-4760-88fd-3fe8617a5399'
    definition: '9'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/10_JAVA'
    Contents: '**'
    TargetFolder: '$(system.defaultworkingdirectory)'

- task: Docker@2
  displayName: 'daytrader-accounts'
  inputs:
    containerRegistry: 'docker-puneet'
    repository: 'puneetsinghgx / daytrader-accounts'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-accountsrepo/daytrader-accountsapp/daytrader-accounts/Dockerfile'
    tags: '15'

- task: Docker@2
  displayName: 'daytrader-gateway'
  inputs:
    containerRegistry: 'docker-puneet'
    repository: 'puneetsinghgx / daytrader-gateway'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-gatewayrepo/daytrader-gatewayapp/daytrader-gateway/Dockerfile'


- task: Docker@2
  displayName: 'daytrader-portfolios'
  inputs:
    containerRegistry: 'docker-puneet'
    repository: 'puneetsinghgx / daytrader-portfolios'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-portfoliosrepo/daytrader-portfoliosapp/daytrader-portfolios/Dockerfile'

- task: Docker@2
  displayName: 'daytrader-quotes'
  inputs:
    containerRegistry: 'docker-puneet'
    repository: 'puneetsinghgx / daytrader-quotes'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-quotesrepo/daytrader-quotesapp/daytrader-quotes/Dockerfile'

- task: Docker@2
  displayName: 'daytrader-web'
  inputs:
    containerRegistry: 'docker-puneet'
    repository: 'puneetsinghgx / daytrader-web'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-webrepo/daytrader-webapp/daytrader-web/Dockerfile'


- script: az extension add -n azure-devops
  displayName: 'Install Azure DevOps Extension'

- script: echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
  env:
    AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
  displayName: 'Login Azure DevOps Extension'

- script: |
    az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project="$(System.TeamProject)" --use-git-aliases true
    commandLine="--branch $branchName --name "30.2 Docker compose with Postman""
    echo "Triggering release creation with: az pipelines run $commandLine"
    az pipelines run $commandLine
