# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  name: Azure Pipelines
  demands: maven


steps:

- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: 'day-trader-java-app/pom.xml'

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'daytrader2'

#- task: Maven@3
#  inputs:
#    mavenPomFile: 'day-trader-java-app/pom.xml'
#    goals: 'deploy'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    mavenVersionOption: 'Default'
#    mavenAuthenticateFeed: false
#    effectivePomSkip: false
#    sonarQubeRunAnalysis: false

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()


#- task: PublishBuildArtifacts@1
#  displayName: 'Publish Artifact: drop'
#  inputs:
#    PathtoPublish: '$(build.artifactstagingdirectory)'
#    artifactName: JAVA_Drop
#  condition: succeededOrFailed()

#First Pipeline of chain
- script: |
    echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
    az devops configure --defaults organization=https://dev.azure.com/AlphaGX project="GXEnablement" --use-git-aliases true
    if [[ "$Repo_Name" == "TfsGit" ]]
    then {
      az pipelines variable-group variable update --id 4 --name Recipe --value R1 -p GXEnablement
      az pipelines run --branch master --name "20.1 Docker Build & Push - ACR" -p GXEnablement
    }
    elif [[ "$Repo_Name" == "GitHub" ]]
    then {
      az pipelines variable-group variable update --id 4 --name Recipe --value R2 -p GXEnablement
      az pipelines run --branch master --name "20.2 Docker Build and Push - DockerHub" -p GXEnablement
    }
    elif [[ "$Repo_Name" == "aws" ]]
    then {
      az pipelines variable-group variable update --id 4 --name Recipe --value R3 -p GXEnablement
      az pipelines run --branch master --name "20.2 Docker Build and Push - DockerHub" -p GXEnablement
    }
    fi
  env:
    AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
    Repo_Name: $(Build.Repository.Provider)
  displayName: 'Triggering next pipeline'