trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: S3Upload@1
  inputs:
    awsCredentials: 'S3-Upload'
    regionName: 'us-east-2'
    bucketName: 'ss-poc-daytrader'
    sourceFolder: 'day-trader-java-app/daytrader-kubernetes-manifests'
    globExpressions: '**'
    filesAcl: 'bucket-owner-full-control'
    createBucket: true

#Invoke AWS Lambda Function to deploy to EKS Kubernetes
- task: CmdLine@2
  inputs:
    script: 'curl -H X-Amz-Invocation-Type: Event https://4z2zwsgpmj.execute-api.us-east-2.amazonaws.com/'